import {test,expect} from '@playwright/test';
test('offline CRUD, persistence, notes, calendar, themes and online sync',async({page,context})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button',{name:'+ Deadline',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('Engineering mathematics assignment');
  await page.getByLabel('Due date',{exact:true}).fill('2026-12-20');
  await page.getByRole('button',{name:'Save deadline',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Engineering mathematics assignment'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Engineering mathematics assignment'})).toBeVisible();
  await context.setOffline(true);
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('Maths revision — offline edit');
  await page.getByRole('button',{name:'Save deadline',exact:true}).click();
  await page.getByRole('button',{name:'Mark complete',exact:true}).click();
  await expect(page.getByRole('button',{name:'Mark incomplete',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Notes',exact:true}).click();
  await page.getByRole('button',{name:'+ Note',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('Formula sheet');
  await page.getByLabel('Note',{exact:true}).fill('<script>alert(1)</script>\nLaplace and Fourier transforms');
  await page.getByRole('button',{name:'Save note',exact:true}).click();
  await expect(page.getByText('<script>alert(1)</script>',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Pin',exact:true}).click();
  await expect(page.getByText('Pinned',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Calendar',exact:true}).click();
  await expect(page.getByRole('button',{name:'Next month'})).toBeVisible();
  await page.getByRole('button',{name:'Account',exact:true}).click();
  await page.getByRole('button',{name:'Off',exact:true}).click();
  await expect(page.locator('body')).toHaveClass('light');
  await context.setOffline(false);
  await page.getByRole('button',{name:'Set up sync',exact:true}).click();
  const email=`browser-${Date.now()}@example.com`;
  await page.getByLabel('Sync server address').fill('http://127.0.0.1:8000');
  await page.getByLabel('Email',{exact:true}).fill(email);
  await page.getByLabel('Password',{exact:true}).fill('test-password-123');
  await page.getByLabel('Action',{exact:true}).selectOption('register');
  await page.getByRole('button',{name:'Connect',exact:true}).click();
  await expect(page.getByRole('heading',{name:email})).toBeVisible();
  await expect(page.locator('#status')).toContainText('Synced');
  page.on('dialog',d=>d.accept());
  await page.getByRole('button',{name:'Copy local items to this account',exact:true}).click();
  await expect(page.locator('#status')).toContainText('Synced');
  await page.getByRole('button',{name:'Deadlines',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Maths revision — offline edit'})).toBeVisible();
  await context.setOffline(true);
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('Offline account update');
  await page.getByRole('button',{name:'Save deadline',exact:true}).click();
  await expect(page.locator('#status')).toContainText('Offline');
  await context.setOffline(false);
  await expect(page.locator('#status')).toContainText('Synced');
  // A separate storage context represents a second device.
  const second=await context.browser().newContext({viewport:{width:390,height:844}});
  const p2=await second.newPage();await p2.goto('http://127.0.0.1:5173');
  await p2.getByRole('button',{name:'Account',exact:true}).click();
  await p2.getByRole('button',{name:'Set up sync',exact:true}).click();
  await p2.getByLabel('Sync server address').fill('http://127.0.0.1:8000');
  await p2.getByLabel('Email',{exact:true}).fill(email);
  await p2.getByLabel('Password',{exact:true}).fill('test-password-123');
  await p2.getByRole('button',{name:'Connect',exact:true}).click();
  await expect(p2.locator('#status')).toContainText('Synced');
  await p2.getByRole('button',{name:'Deadlines',exact:true}).click();
  await expect(p2.getByRole('heading',{name:'Offline account update'})).toBeVisible();
  await expect(p2.getByRole('button',{name:'Mark incomplete',exact:true})).toBeVisible();
  await p2.getByRole('button',{name:'Notes',exact:true}).click();
  await expect(p2.getByRole('heading',{name:'Formula sheet'})).toBeVisible();
  await second.close();
  await expect(page.locator('.toast')).toHaveCount(0,{timeout:7000});
  await page.screenshot({path:'test-results/phone-preview.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);expect(errors).toEqual([]);
});
