import './style.css';
import logo from './logo.svg';
import {Preferences} from '@capacitor/preferences';
import {App} from '@capacitor/app';
import {openDB,all,save,applyRemote,importGuest} from './store.js';
import {permission,reminders} from './reminders.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let session={},scope='guest',items=[],tab='home',query='',filter='all',sort='due',selected=today(),month=new Date(new Date().getFullYear(),new Date().getMonth(),1),busy=false;
let theme='dark',notify=false,status='Saved on this device';
const root=$('#app'),dialog=document.createElement('dialog');document.body.append(dialog);
function toast(message){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),5000);}
async function persistSession(){await Preferences.set({key:'session',value:JSON.stringify(session)});}
async function load(){items=await all(scope);render();try{await reminders(items,notify);}catch{toast('Saved. Phone reminders could not be updated.');}}
function active(){return items.filter(x=>!x.deleted);}
function deadlineCard(x){const late=!x.completed&&x.due<today();return `<article class="card ${x.completed?'done':''}"><button class="check" data-action="toggle" data-id="${x.id}" aria-label="${x.completed?'Mark incomplete':'Mark complete'}">${x.completed?'✓':'○'}</button><div class="body"><span class="pill ${esc(x.priority)}">${esc(x.priority)}</span><span class="pill">${esc(x.category)}</span><h3>${esc(x.title)}</h3><small class="${late?'late':''}">${x.completed?'Completed · ':late?'Overdue · ':x.due===today()?'Due today · ':''}${esc(x.due)}</small><div class="actions"><button data-action="edit" data-id="${x.id}">Edit</button><button data-action="delete" data-id="${x.id}" class="danger">Delete</button></div></div></article>`;}
function noteCard(x){return `<article class="card"><div class="body"><span class="pill">${x.pinned?'Pinned':'Note'}</span><h3>${esc(x.title)}</h3><p>${esc(x.content.slice(0,180))}${x.content.length>180?'…':''}</p><div class="actions"><button data-action="edit" data-id="${x.id}">Open</button><button data-action="pin" data-id="${x.id}">${x.pinned?'Unpin':'Pin'}</button><button data-action="delete" data-id="${x.id}" class="danger">Delete</button></div></div></article>`;}
function renderList(){if(!$('#list'))return;let rows=active().filter(x=>x.kind===(tab==='notes'?'note':'deadline')).filter(x=>(x.title+' '+(x.category||'')+' '+(x.content||'')).toLowerCase().includes(query.toLowerCase()));if(tab==='calendar')rows=rows.filter(x=>x.due===selected);if(tab!=='notes'){rows=rows.filter(x=>filter==='all'||(filter==='done'?x.completed:filter==='open'?!x.completed:!x.completed&&x.due<today()));rows.sort((a,b)=>sort==='priority'?({High:0,Medium:1,Low:2}[a.priority]-{High:0,Medium:1,Low:2}[b.priority]):a.due.localeCompare(b.due));}else rows.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updated.localeCompare(a.updated));$('#list').innerHTML=rows.length?rows.map(tab==='notes'?noteCard:deadlineCard).join(''):'<div class="empty">Nothing here yet. Add something to get started.</div>';}
function toolbar(){return `<div class="toolbar"><input id="search" type="search" aria-label="Search" placeholder="Search ${tab==='notes'?'notes':'deadlines'}…" value="${esc(query)}">${tab==='notes'?'':`<select id="filter" aria-label="Filter"><option value="all">All</option><option value="open">Pending</option><option value="done">Completed</option><option value="late">Overdue</option></select><select id="sort" aria-label="Sort"><option value="due">Due date</option><option value="priority">Priority</option></select>`}<button class="primary" data-action="add">+ ${tab==='notes'?'Note':'Deadline'}</button></div>`;}
function calendar(){const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const offset=(month.getDay()+6)%7;let html='<div class="row"><button data-action="prev" aria-label="Previous month">‹</button><h2>'+month.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</h2><button data-action="next" aria-label="Next month">›</button></div><div class="calendar">'+['M','T','W','T','F','S','S'].map(s=>`<small>${s}</small>`).join('')+'<span></span>'.repeat(offset);for(let i=1;i<=count;i++){const d=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(i).padStart(2,'0')}`;html+=`<button data-action="day" data-date="${d}" class="${d===selected?'selected':active().some(x=>x.kind==='deadline'&&x.due===d)?'has':''}" aria-label="${d}">${i}</button>`;}return html+'</div><p class="muted">Deadlines for '+selected+'</p>';}
function account(){return `<div class="panel"><span class="tag">Your workspace</span><h2>${esc(session.email||'On this phone')}</h2><p>${session.email?'Your account has its own offline workspace. Sign in again if your session expires.':'You can use DeadlineHub without an account. Connect an account to sync across devices.'}</p><div class="actions"><button class="primary" data-action="connect">${session.email?'Sign in / switch account':'Set up sync'}</button>${session.email?'<button data-action="sync">Sync now</button><button data-action="logout">Use local workspace</button><button data-action="import">Copy local items to this account</button>':''}</div></div><div class="panel"><h2>Make it yours</h2><div class="row"><p>Light appearance</p><button data-action="theme">${theme==='light'?'On':'Off'}</button></div><div class="row"><p>Phone reminders at 9 AM on the due date</p><button data-action="notify">${notify?'On':'Enable'}</button></div><p>Reminders use the phone’s time zone. Android battery settings can delay delivery. Sync runs when the app is open or resumed.</p></div><div class="panel"><h2>Your data</h2><p>Changes are saved on this device first. Removing the app or clearing its data removes unsynced items. Local workspace items stay separate from account items.</p><p>${esc(status)}</p></div>`;}
function render(){document.body.classList.toggle('light',theme==='light');const ds=active().filter(x=>x.kind==='deadline'),done=ds.filter(x=>x.completed).length;root.innerHTML=`<header><div class="brand"><img src="${logo}" alt="">DeadlineHub</div><div class="status" id="status">${esc(status)}</div></header><main><div class="intro"><span class="tag">${tab==='home'?'A little clarity. Every day.':tab==='notes'?'Capture what matters':tab==='calendar'?'See the month ahead':'Personal space'}</span><h1>${{home:'Make room for what’s next.',notes:'Your notes',calendar:'Your calendar',account:'Account & settings'}[tab]}</h1>${tab==='home'?'<p class="muted">Your deadlines, one step at a time.</p>':''}</div>${tab==='account'?account():`${tab==='home'?`<div class="stats"><div class="stat"><strong>${ds.length-done}</strong><span>Pending</span></div><div class="stat"><strong>${done}</strong><span>Completed</span></div><div class="stat"><strong>${ds.filter(x=>!x.completed&&x.due<today()).length}</strong><span>Overdue</span></div></div><div class="progress" aria-label="Completion progress"><div style="width:${ds.length?Math.round(done/ds.length*100):0}%"></div></div>`:''}${tab==='calendar'?calendar():''}${toolbar()}<div class="cards" id="list"></div>`}</main><nav class="nav" aria-label="Main navigation">${[['home','Deadlines'],['calendar','Calendar'],['notes','Notes'],['account','Account']].map(([id,label])=>`<button data-action="tab" data-tab="${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}>${label}</button>`).join('')}</nav>`;if($('#filter'))$('#filter').value=filter;if($('#sort'))$('#sort').value=sort;renderList();}
function modal(html,submit){dialog.innerHTML=html;dialog.showModal();dialog.querySelector('[data-close]')?.addEventListener('click',()=>dialog.close());dialog.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await submit(new FormData(e.target));dialog.close();}catch(err){dialog.querySelector('.form-error').textContent=err.message;}finally{button.disabled=false;}});}
function editor(item){const kind=item?.kind||(tab==='notes'?'note':'deadline');modal(`<h2>${item?'Edit':'New'} ${kind}</h2><form class="stack"><label>Title<input name="title" required maxlength="180" value="${esc(item?.title||'')}"></label>${kind==='deadline'?`<label>Due date<input name="due" type="date" required value="${esc(item?.due||(tab==='calendar'?selected:today()))}"></label><label>Category<input name="category" maxlength="60" value="${esc(item?.category||'Study')}"></label><label>Priority<select name="priority">${['Low','Medium','High'].map(p=>`<option ${p===(item?.priority||'Medium')?'selected':''}>${p}</option>`).join('')}</select></label>`:`<label>Note<textarea name="content" maxlength="50000">${esc(item?.content||'')}</textarea></label>`}<div class="form-error" role="alert"></div><div class="actions"><button class="primary" type="submit">Save ${kind}</button><button type="button" data-close>Cancel</button></div></form>`,async data=>{const fields=Object.fromEntries(data);fields.title=fields.title.trim();if(!fields.title)throw Error('Please enter a title.');await save(scope,{id:crypto.randomUUID(),rev:0,completed:false,pinned:false,deleted:false,...item,...fields,kind,updated:new Date().toISOString()});await load();void sync();});}
async function request(path,body,auth=session){const response=await fetch(auth.server+path,{method:'POST',headers:{'Content-Type':'application/json',...(auth.token?{Authorization:'Bearer '+auth.token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({error:'The server did not return a valid response.'}));if(!response.ok)throw Error(data.error||'Server request failed.');return data;}
function connect(){modal(`<h2>Connect your account</h2><form class="stack"><label>Sync server address<input name="server" type="url" required placeholder="https://your-server.example" value="${esc(session.server||'')}"></label><label>Email<input name="email" type="email" required autocomplete="username" value="${esc(session.email||'')}"></label><label>Password<input name="password" type="password" required minlength="10" maxlength="256" autocomplete="current-password"></label><label>Action<select name="mode" aria-label="Action"><option value="login">Sign in</option><option value="register">Create account</option></select></label><p class="muted">Use the server supplied with this project. First sign-in needs internet; your account then works offline.</p><div class="form-error" role="alert"></div><div class="actions"><button class="primary" type="submit">Connect</button><button type="button" data-close>Cancel</button></div></form>`,async data=>{if(busy)throw Error('Please wait for the current sync to finish.');const url=new URL(data.get('server'));if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw Error('Use an HTTPS server address.');if(url.username||url.password||url.search||url.hash)throw Error('Enter a plain server URL.');const server=url.href.replace(/\/$/,'');const result=await request('/api/'+data.get('mode'),{email:data.get('email'),password:data.get('password')},{server});session={server,email:result.email,token:result.token,userId:result.userId};scope=JSON.stringify([server,result.userId]);await persistSession();await load();void sync();});}
async function sync(){if(busy||!session.token)return;if(!navigator.onLine){status='Offline · changes saved on this device';renderStatus();return;}busy=true;status='Syncing…';renderStatus();const target=scope,auth={...session};try{const sent=(await all(target)).filter(x=>x.dirty);const out=await request('/api/sync',{changes:sent},auth);await applyRemote(target,out.items,sent);status=out.conflicts?'Synced · conflicting edits kept as copies':'Synced at '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(scope===target)await load();if(out.conflicts)toast('Conflicting edits were preserved. Review conflict copies.');}catch(err){status='Saved locally · sync unavailable';renderStatus();if(tab==='account')toast(err.message);}finally{busy=false;}}
function renderStatus(){if($('#status'))$('#status').textContent=status;}
root.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;renderList();}});
root.addEventListener('change',e=>{if(e.target.id==='filter')filter=e.target.value;if(e.target.id==='sort')sort=e.target.value;renderList();});
root.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const x=items.find(i=>i.id===el.dataset.id);try{switch(el.dataset.action){case'tab':tab=el.dataset.tab;query='';render();break;case'add':editor();break;case'edit':editor(x);break;case'toggle':await save(scope,{...x,completed:!x.completed,updated:new Date().toISOString()});await load();void sync();break;case'pin':await save(scope,{...x,pinned:!x.pinned,updated:new Date().toISOString()});await load();void sync();break;case'delete':if(confirm('Delete “'+x.title+'”?')){await save(scope,{...x,deleted:true});await load();void sync();}break;case'day':selected=el.dataset.date;render();break;case'prev':case'next':month=new Date(month.getFullYear(),month.getMonth()+(el.dataset.action==='next'?1:-1),1);render();break;case'theme':theme=theme==='dark'?'light':'dark';await Preferences.set({key:'theme',value:theme});render();break;case'notify':if(!notify)await permission();notify=!notify;await Preferences.set({key:'notify',value:String(notify)});await load();break;case'connect':connect();break;case'sync':await sync();break;case'logout':if(busy)throw Error('Wait for sync to finish.');if(confirm('Return to your local workspace? Account data remains stored on this phone.')){session={};scope='guest';status='Saved on this device';await persistSession();await load();}break;case'import':if(confirm('Copy local workspace items into this account? Repeating this makes duplicate copies.')){const count=await importGuest(scope);await load();toast(count+' items copied');void sync();}break;}}catch(err){toast(err.message);}});
try{await openDB();session=JSON.parse((await Preferences.get({key:'session'})).value||'{}');scope=session.userId?JSON.stringify([session.server,session.userId]):'guest';theme=(await Preferences.get({key:'theme'})).value||'dark';notify=(await Preferences.get({key:'notify'})).value==='true';await load();void sync();window.addEventListener('online',()=>void sync());window.addEventListener('offline',()=>{status='Offline · changes saved on this device';renderStatus();});setInterval(()=>void sync(),60000);App.addListener('appStateChange',({isActive})=>{if(isActive)void sync();});App.addListener('backButton',()=>{if(dialog.open)dialog.close();else if(tab!=='home'){tab='home';render();}else App.minimizeApp();});}catch(err){root.innerHTML='<main><h1>Unable to open storage</h1><p>'+esc(err.message)+'</p><p>Restart the app. Do not clear app data if you have unsynced work.</p></main>';}
